import { QueryInterface } from 'sequelize';

export default {
  up: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkInsert(
      'addresses',
      [
        {
          street: 'Janete Ângela Carneiro Jacomel',
          number: 50,
          district: 'Olarias',
          city: 'Ponta Grossa',
          state: 'PR',
          country: 'Brasil',
          patientId: 1,
        },
        {
          street: 'Rua 2',
          number: 2,
          district: 'Bairro 2 ',
          city: 'Cidade 2',
          state: 'Estado 2',
          country: 'País 2',
          patientId: 2,
        },
        {
          street: 'Rua 3',
          number: 3,
          district: 'Bairro 3',
          city: '123',
          state: 'Estado 3',
          country: 'País 3',
          patientId: 3,
        },
        {
          patientId: 4,
          street: 'Rua 4',
          district: 'Bairro 4',
          number: '123',
          city: 'Cidade 4',
          state: 'Estado 4',
          country: 'País 4',
        },
        {
          patientId: 5,
          street: 'Rua 5',
          district: 'Bairro 5',
          number: '456',
          city: 'Cidade 5',
          state: 'Estado 5',
          country: 'País 5',
        },
        {
          patientId: 6,
          street: 'Rua 6',
          district: 'Bairro 6',
          number: '789',
          city: 'Cidade 6',
          state: 'Estado 6',
          country: 'País 6',
        },
        {
          patientId: 7,
          street: 'Rua 7',
          district: 'Bairro 7',
          number: '1011',
          city: 'Cidade 7',
          state: 'Estado 7',
          country: 'País 7',
        },
        {
          patientId: 8,
          street: 'Rua 8',
          district: 'Bairro 8',
          number: '1213',
          city: 'Cidade 8',
          state: 'Estado 8',
          country: 'País 8',
        },
        {
          patientId: 9,
          street: 'Rua 9',
          district: 'Bairro 9',
          number: '1415',
          city: 'Cidade 9',
          state: 'Estado 9',
          country: 'País 9',
        },
        {
          patientId: 10,
          street: 'Rua 10',
          district: 'Bairro 10',
          number: '1617',
          city: 'Cidade 10',
          state: 'Estado 10',
          country: 'País 10',
        },
        {
          patientId: 11,
          street: 'Rua 11',
          district: 'Bairro 11',
          number: '1819',
          city: 'Cidade 11',
          state: 'Estado 11',
          country: 'País 11',
        },
        {
          patientId: 12,
          street: 'Rua 12',
          district: 'Bairro 12',
          number: '2021',
          city: 'Cidade 12',
          state: 'Estado 12',
          country: 'País 12',
        },
        {
          patientId: 13,
          street: 'Rua 13',
          district: 'Bairro 13',
          number: '2223',
          city: 'Cidade 13',
          state: 'Estado 13',
          country: 'País 13',
        },
        {
          patientId: 14,
          street: 'Rua 14',
          district: 'Bairro 14',
          number: '2425',
          city: 'Cidade 14',
          state: 'Estado 14',
          country: 'País 14',
        },
        {
          patientId: 15,
          street: 'Rua 15',
          district: 'Bairro 15',
          number: '2627',
          city: 'Cidade 15',
          state: 'Estado 15',
          country: 'País 15',
        },
        {
          patientId: 16,
          street: 'Rua 16',
          district: 'Bairro 16',
          number: '2829',
          city: 'Cidade 16',
          state: 'Estado 16',
          country: 'País 16',
        },
        {
          patientId: 17,
          street: 'Rua 17',
          district: 'Bairro 17',
          number: '3031',
          city: 'Cidade 17',
          state: 'Estado 17',
          country: 'País 17',
        },
        {
          patientId: 18,
          street: 'Rua 18',
          district: 'Bairro 18',
          number: '3233',
          city: 'Cidade 18',
          state: 'Estado 18',
          country: 'País 18',
        },
      ],

      {},
    );
  },
  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkDelete('addresses', {});
  },
};
